[profile.default]
leak-timeout = "200ms"

[[profile.default.overrides]]
filter = 'test(/^tests::test_threads_2_::/)'
threads-required = 2

[[profile.default.overrides]]
filter = 'test(/^tests::test_threads_12_::/)'
threads-required = 12

[[profile.default.overrides]]
filter = 'test(/^tests::test_threads_32_::/)'
threads-required = 32

[[profile.default.overrides]]
filter = 'test(/^tests::test_threads_1000_::/)'
threads-required = 1000

